###
### N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
###

@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1MTcwNDkyOTgsImlzcyI6Imh0dHBzOi8vaHNrYS5kZS9zaG9wL0p1ZXJnZW5aaW1tZXJtYW5uIiwic3ViIjoiMjAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAxIiwianRpIjoiZGY0MzM4ZDQtZGQ3Yi00ZDI4LTk1NTEtMzUyYWM5ZWExMGUwIiwiZXhwIjoxNTE3MTM1Njk4fQ.oIXlxJ1qYpFFz4f_5eSLuCTeqc4dSnVwfXZIlPqtQLdbTFgSefyHRVqa2j4QUo9ztF_Ipy2x-prVQZ3NzKDzjBGPqPpwQePDvhblRR9fyKx6GeFncX8ncak4oIzQRkL--M5hQgY-8lmot3bn_lIwGiuG_mjEiW6AZgyTXISmuTJEDp2KDh0JyCGaWh1Kk7TE3DlSbJqaLMQE0JJsSlGXsH55ukztS6PIHmpdp-rME8ayFjXV7rQGIWLQmLCcApoY284g5kAxlYeVjoBhTVmmrjY194JgAJLjWJ7zDv0f2IffaoZnOLUNar7KUBdO1c0ECYiMBqLSxQ3ZO4vo-02NNA
@host = 127.0.0.1:8444
@basic_auth_admin = Basic YWRtaW46cA

### Login
POST https://{{host}}/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=p

### Suche alle Kunden
https://{{host}}
Authorization: {{basic_auth_admin}}

### Suche mit vorhandener Kunde-ID
https://{{host}}/kunden/00000000-0000-0000-0000-000000000001

### Suche mit vorhandener Kunde-ID und Versionsnummer
https://{{host}}/kunden/00000000-0000-0000-0000-000000000001
If-None-Match: 0

### Optionen zu Kunde-ID
OPTIONS https://{{host}}/kunden/00000000-0000-0000-0000-000000000001

### Suche mit ungueltiger Kunde-ID
https://{{host}}/kunden/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY

### Suche mit nicht-vorhandener Kunde-ID
https://{{host}}/kunden/99999999-9999-9999-9999-999999999999

### Suche mit vorhandenem Nachname
https://{{host}}/kunden?nachname=a

### Suche mit vorhandener ISBN-Nummber
https://{{host}}/kunden?isbn=000-0-00000-000-1

### Suche mit vorhandenen Interessenn
https://{{host}}/kunden?sport=true&lesen=true

### Suche mit gueltiger Kundeart
https://{{host}}/kunden?geschlecht=W

### Suche mit gueltigem Rating
https://{{host}}/kunden?rating=1

### Suche newslettere Kunden
https://{{host}}/kunden?newsletter=true

### Neuer Kunde anlegen
POST https://{{host}}/kunden
Content-Type: application/json
Authorization: {{token}}

< ./config/rest/kunde-neu.json

### Neuer Kunde mit ungueltigen Daten anlegen
POST https://{{host}}/kunden
Content-Type: application/json
Authorization: {{token}}

< ./config/rest/kunde-neu-invalid.json

### Vorhandenes Kunde aktualisieren
PUT https://{{host}}/kunden/00000000-0000-0000-0000-000000000003
Content-Type: application/json
Authorization: {{token}}
If-Match: 0

< ./config/rest/kunde-3-put.json

### Vorhandenes Kunde *OHNE* Versionsnummer aktualisieren
PUT https://{{host}}/kunden/00000000-0000-0000-0000-000000000003
Content-Type: application/json
Authorization: {{token}}

< ./config/rest/kunde-3-put.json

### Vorhandenes Kunde mit ungueltigen Daten aktualisieren
PUT https://{{host}}/kunden/00000000-0000-0000-0000-000000000003
Content-Type: application/json
Authorization: {{token}}
If-Match: 0

< ./config/rest/kunde-3-put-invalid.json

### Loeschen eines vorhandenen Kundees
DELETE https://{{host}}/kunden/00000000-0000-0000-0000-000000000005
Authorization: {{token}}

###
